//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aufbauwerk.Asterisk.Relay.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aufbauwerk.Asterisk.Relay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The object has already been initialized. ähnelt.
        /// </summary>
        internal static string Configuration_AlreadyInitialized {
            get {
                return ResourceManager.GetString("Configuration_AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Asterisk Manager Interface #{0} configuration error: {1} ähnelt.
        /// </summary>
        internal static string Configuration_AsteriskManagerInterfaceError {
            get {
                return ResourceManager.GetString("Configuration_AsteriskManagerInterfaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Board #{0} configuration error: {1} ähnelt.
        /// </summary>
        internal static string Configuration_BoardError {
            get {
                return ResourceManager.GetString("Configuration_BoardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More than one board have been defined at address {1} on port {0}. ähnelt.
        /// </summary>
        internal static string Configuration_DuplicateBoardAdddress {
            get {
                return ResourceManager.GetString("Configuration_DuplicateBoardAdddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More than one Asterisk Manager Interface refer to {0}. ähnelt.
        /// </summary>
        internal static string Configuration_DuplicateManagerBaseUri {
            get {
                return ResourceManager.GetString("Configuration_DuplicateManagerBaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name &quot;{0}&quot; is used for more than one switch. ähnelt.
        /// </summary>
        internal static string Configuration_DuplicateSwitchName {
            get {
                return ResourceManager.GetString("Configuration_DuplicateSwitchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The boards&apos;s address must be greater than 0. ähnelt.
        /// </summary>
        internal static string Configuration_InvalidBoardAddress {
            get {
                return ResourceManager.GetString("Configuration_InvalidBoardAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No switch named &quot;{0}&quot; has been found. ähnelt.
        /// </summary>
        internal static string Configuration_InvalidSwitchName {
            get {
                return ResourceManager.GetString("Configuration_InvalidSwitchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The connection parameters are invalid: {0} ähnelt.
        /// </summary>
        internal static string Configuration_MalformedUri {
            get {
                return ResourceManager.GetString("Configuration_MalformedUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The list of Asterisk Manager Interfaces is missing. ähnelt.
        /// </summary>
        internal static string Configuration_MissingAsteriskManagerInterfaces {
            get {
                return ResourceManager.GetString("Configuration_MissingAsteriskManagerInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The list of boards is missing. ähnelt.
        /// </summary>
        internal static string Configuration_MissingBoards {
            get {
                return ResourceManager.GetString("Configuration_MissingBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The format string for converting switch names to device names is missing. ähnelt.
        /// </summary>
        internal static string Configuration_MissingDeviceNameFormat {
            get {
                return ResourceManager.GetString("Configuration_MissingDeviceNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The host name is missing. ähnelt.
        /// </summary>
        internal static string Configuration_MissingHostname {
            get {
                return ResourceManager.GetString("Configuration_MissingHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The operand is missing. ähnelt.
        /// </summary>
        internal static string Configuration_MissingOperand {
            get {
                return ResourceManager.GetString("Configuration_MissingOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password is missing. ähnelt.
        /// </summary>
        internal static string Configuration_MissingPassword {
            get {
                return ResourceManager.GetString("Configuration_MissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The port name is missing. ähnelt.
        /// </summary>
        internal static string Configuration_MissingPortName {
            get {
                return ResourceManager.GetString("Configuration_MissingPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The function for relay #{0} is missing. ähnelt.
        /// </summary>
        internal static string Configuration_MissingRelay {
            get {
                return ResourceManager.GetString("Configuration_MissingRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The list of switches is missing. ähnelt.
        /// </summary>
        internal static string Configuration_MissingSwitches {
            get {
                return ResourceManager.GetString("Configuration_MissingSwitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name of the switch is missing. ähnelt.
        /// </summary>
        internal static string Configuration_MissingSwitchName {
            get {
                return ResourceManager.GetString("Configuration_MissingSwitchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user name is missing. ähnelt.
        /// </summary>
        internal static string Configuration_MissingUsername {
            get {
                return ResourceManager.GetString("Configuration_MissingUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Op({0}): {1} ähnelt.
        /// </summary>
        internal static string Configuration_OperandError {
            get {
                return ResourceManager.GetString("Configuration_OperandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The port number is either less than 1 or greater than 65535. ähnelt.
        /// </summary>
        internal static string Configuration_PortOutOfRange {
            get {
                return ResourceManager.GetString("Configuration_PortOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The read timeout must be greater than 0. ähnelt.
        /// </summary>
        internal static string Configuration_ReadTimeoutOutOfRange {
            get {
                return ResourceManager.GetString("Configuration_ReadTimeoutOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The object is already being initialized. ähnelt.
        /// </summary>
        internal static string Configuration_ReenteredInitializing {
            get {
                return ResourceManager.GetString("Configuration_ReenteredInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Relay #{0}: {1} ähnelt.
        /// </summary>
        internal static string Configuration_RelayError {
            get {
                return ResourceManager.GetString("Configuration_RelayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The retry interval must be non-negative. ähnelt.
        /// </summary>
        internal static string Configuration_RetryIntervalOutOfRange {
            get {
                return ResourceManager.GetString("Configuration_RetryIntervalOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serial port configuration error: {0} ähnelt.
        /// </summary>
        internal static string Configuration_SerialPortError {
            get {
                return ResourceManager.GetString("Configuration_SerialPortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch #{0} configuration error: {1} ähnelt.
        /// </summary>
        internal static string Configuration_SwitchError {
            get {
                return ResourceManager.GetString("Configuration_SwitchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The write timeout must be greater than 0. ähnelt.
        /// </summary>
        internal static string Configuration_WriteTimeoutOutOfRange {
            get {
                return ResourceManager.GetString("Configuration_WriteTimeoutOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Port Manager ähnelt.
        /// </summary>
        internal static string Hardware_BackgroundTaskName {
            get {
                return ResourceManager.GetString("Hardware_BackgroundTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The board #{1} on port {0} is out of range and will be ignored. ähnelt.
        /// </summary>
        internal static string Hardware_BoardAddressOutOfRange {
            get {
                return ResourceManager.GetString("Hardware_BoardAddressOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No board for address #{1} on port {0} has been configured. ähnelt.
        /// </summary>
        internal static string Hardware_BoardConfigurationMissing {
            get {
                return ResourceManager.GetString("Hardware_BoardConfigurationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The command {1} has been sent to board #{2} on port {0} but the response originates from board #{3}. ähnelt.
        /// </summary>
        internal static string Hardware_DifferentBoardAddress {
            get {
                return ResourceManager.GetString("Hardware_DifferentBoardAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The command {1} has been sent to board #{2} on port {0} but the response is for an op-code of {3}. ähnelt.
        /// </summary>
        internal static string Hardware_DifferentOpCode {
            get {
                return ResourceManager.GetString("Hardware_DifferentOpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The checksum of the response to command {1} from board #{2} on port {0} is invalid. ähnelt.
        /// </summary>
        internal static string Hardware_InvalidChecksum {
            get {
                return ResourceManager.GetString("Hardware_InvalidChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An I/O operation on port {0} timed out. ähnelt.
        /// </summary>
        internal static string Hardware_OperationTimedOut {
            get {
                return ResourceManager.GetString("Hardware_OperationTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The initialization of port {0} is complete.
        ///Number of boards connected: {1} ähnelt.
        /// </summary>
        internal static string Hardware_SetupComplete {
            get {
                return ResourceManager.GetString("Hardware_SetupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Asterisk Manager Connection to {0} ähnelt.
        /// </summary>
        internal static string Manager_BackgroundTaskName {
            get {
                return ResourceManager.GetString("Manager_BackgroundTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The switch states have been successfully synced with {0}. ähnelt.
        /// </summary>
        internal static string Manager_SyncComplete {
            get {
                return ResourceManager.GetString("Manager_SyncComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The action &quot;{2}&quot; for switch &quot;{1}&quot; has been received from {0}.
        ///The event will be ignored because the action is unknown. ähnelt.
        /// </summary>
        internal static string Manager_UnknownAction {
            get {
                return ResourceManager.GetString("Manager_UnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A relay event for switch &quot;{1}&quot; has been received from {0}.
        ///The event will be ignored since no switch with that name is registered. ähnelt.
        /// </summary>
        internal static string Manager_UnknownSwitch {
            get {
                return ResourceManager.GetString("Manager_UnknownSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following error occured in {0}: {1} ähnelt.
        /// </summary>
        internal static string Program_BackgroundTaskException {
            get {
                return ResourceManager.GetString("Program_BackgroundTaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A switch name must be provided. ähnelt.
        /// </summary>
        internal static string Remoting_SwitchNameRequired {
            get {
                return ResourceManager.GetString("Remoting_SwitchNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No switch named &quot;{0}&quot; has been configured. ähnelt.
        /// </summary>
        internal static string Remoting_SwitchNotFound {
            get {
                return ResourceManager.GetString("Remoting_SwitchNotFound", resourceCulture);
            }
        }
    }
}
