//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1008
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aufbauwerk.Asterisk.Relay.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AsteriskEnabled {
            get {
                return ((bool)(this["AsteriskEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemotingEnabled {
            get {
                return ((bool)(this["RemotingEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Aufbauwerk.Asterisk.Relay.Configuration.SerialPort SerialPort {
            get {
                return ((global::Aufbauwerk.Asterisk.Relay.Configuration.SerialPort)(this["SerialPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Aufbauwerk.Asterisk.Relay.Configuration.Board[] Boards {
            get {
                return ((Aufbauwerk.Asterisk.Relay.Configuration.Board[])(this["Boards"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Aufbauwerk.Asterisk.Relay.Configuration.Switch[] Switches {
            get {
                return ((Aufbauwerk.Asterisk.Relay.Configuration.Switch[])(this["Switches"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Aufbauwerk.Asterisk.Relay.Configuration.AsteriskManagerInterface[] AsteriskManagerInterfaces {
            get {
                return ((Aufbauwerk.Asterisk.Relay.Configuration.AsteriskManagerInterface[])(this["AsteriskManagerInterfaces"]));
            }
        }
    }
}
